components:
  requestBodies:
    CreatePetRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreatePetBody'
      description: JSON object with data to create a new pet
      required: true
    UpdatePetRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdatePetBody'
      description: JSON object with data to update a pet
      required: true
  schemas:
    ApiError:
      properties:
        code:
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
    CategorySchema:
      properties:
        id:
          description: ID
          readOnly: true
          type: integer
        name:
          description: A name
          type: string
        size:
          description: Size of name
          format: int64
          type: integer
      required:
      - name
      type: object
    CreatePetBody:
      properties:
        name:
          type: string
      required:
      - name
      type: object
    PetSchema:
      properties:
        categories:
          description: Has these categories
          items:
            $ref: '#/components/schemas/CategorySchema'
          type: array
        created_at:
          description: When this item was created
          format: date-time
          readOnly: true
          title: Created At
          type: string
        name:
          type: string
      type: object
    UpdatePetBody:
      properties:
        categories:
          items:
            $ref: '#/components/schemas/CategorySchema'
          type: array
        name:
          type: string
      type: object
  securitySchemes:
    Bearer:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: Swagger Petstore
  license:
    name: MIT
    url: https://en.wikipedia.org/wiki/MIT_License
  termsOfService: http://example.com/terms/
  title: Swagger Petstore
  version: 1.0.0
openapi: 3.0.2
paths:
  /ping:
    get:
      responses:
        '200':
          content:
            text/plain:
              schema:
                type: string
          description: It must be a PONG
      summary: Ping our API
      tags:
      - default
  /tests/long-uri:
    get:
      responses:
        '414':
          description: Request URI too large.
        default:
          content:
            text/plain:
              schema:
                type: string
          description: Unexpected error
      summary: If the URI is long then throw an error
      tags:
      - default
  /category/{id}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategorySchema'
          description: Information about a category
      tags: []
    parameters:
    - description: ID of a Category
      in: path
      name: id
      required: true
      schema:
        type: string
  /pet/{id}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetSchema'
          description: An object a Pet
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: An object does not exist
      security:
      - Bearer: []
      summary: Get a pet
      tags:
      - pets
    parameters:
    - description: ID of a Pet
      in: path
      name: id
      required: true
      schema:
        type: string
    patch:
      requestBody:
        $ref: '#/components/requestBodies/UpdatePetRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetSchema'
          description: Response an object of updated pet
      security:
      - Bearer: []
      summary: Update a pet
      tags:
      - pets
    post:
      requestBody:
        $ref: '#/components/requestBodies/CreatePetRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetSchema'
          description: A pet is created
      security:
      - Bearer: []
      summary: Create a pet
      tags:
      - pets
servers:
- description: Production Server
  url: https://production.example.com/
- description: Development Server
  url: https://localhost:8000/
tags:
- description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: http://swagger.io
  name: pets
- description: Basic APIs
  name: default
