components:
  schemas:
    CategorySchema:
      properties:
        id:
          description: ID
          readOnly: true
          type: integer
        name:
          description: A name
          type: string
        size:
          description: Size of name
          format: int64
          type: integer
      required:
      - name
      type: object
    PetSchema:
      properties:
        categories:
          description: Has these categories
          items:
            $ref: '#/components/schemas/CategorySchema'
          type: array
        created_at:
          default: When item was created
          format: date-time
          readOnly: true
          type: string
        name:
          type: string
      type: object
  securitySchemes:
    Bearer:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: Swagger Petstore
  termsOfService: http://example.com/terms/
  title: Swagger Petstore
  version: 1.0.0
openapi: 3.0.2
paths:
  /category/{id}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategorySchema'
          description: Information about a category
    parameters:
    - description: ID of a Category
      in: path
      name: id
      required: true
      schema:
        type: string
  /pet/{id}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetSchema'
          description: An object a Pet
      security:
      - Bearer: []
    parameters:
    - description: ID of a Pet
      in: path
      name: id
      required: true
      schema:
        type: string
    patch:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetSchema'
          description: Response an object of updated pet
    summary: Get or Update a pet by its ID
servers:
- description: Production Server
  url: https://production.example.com/
- description: Development Server
  url: https://localhost:8000/

